# action.yml
name: 'Hubocular'
description: 'Mine your repo in you Actioins'
inputs:
  repo-name:  # id of input
    description: 'Repo name'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo-name }}
