# action.yml
name: 'Hubocular'
description: 'Mine your repo in you Actioins'
inputs:
  repo-name:  # id of input
    description: 'Repo name'
    required: true
  github-token:
    description: "Token to use for GitHub"
    required: true
runs:
  #using: 'docker'
  #image: 'Dockerfile'
  using: 'composite'
  services:

      arangodb:
        image: arangodb:3.7
        ports:  
          - 8529:8529
        env: 
          ARANGO_ROOT_PASSWORD: openSesame
  steps:

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Checkout Repository to scan
      uses: actions/checkout@v3
      with:
        ref: develop
        fetch-depth: 0
        path: test

    - name: Set .pupilrc variables
      uses: microsoft/variable-substitution@v1   
      with:
        files: .binocularrc_ci
      env:
        github.auth.token: ${{ inputs.github-token }}

    - name: Rename binocularrc
      run: mv .binocularrc_ci .binocularrc 

    - name: Set node version
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Run binocular
      run: node binocular.js --no-open --no-server ./test

    - name: Build
      run: npm run build
    #- name: Publish artifact
     #   uses: actions/upload-artifact@v3
      #  with:
       #   name: binocular_ui
        #  path: ./test.txt
  #args:
   # - ${{ inputs.repo-name }}
