# action.yml
name: 'Hubocular'
description: 'Mine your repo in you Actioins'
inputs:
  repo-name:  # id of input
    description: 'Repo name'
    required: true
  github-token:
    description: "Token to use for GitHub"
    required: true
runs:
  using: 'composite'
  steps:

    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        repository: INSO-TUWien/Binocular
        ref: develop

    - name: Checkout Repository to scan
      uses: actions/checkout@v3
      with:
        repository: INSO-TUWien/Binocular
        ref: develop
        fetch-depth: 0
        path: test

    - name: Set .pupilrc variables
      uses: microsoft/variable-substitution@v1   
      with:
        files: .binocularrc_ci
      env:
        github.auth.token: ${{ inputs.github-token }}

    - name: Rename binocularrc
      run: mv .binocularrc_ci .binocularrc 
      shell: bash

    - name: Set node version
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Run binocular
      run: node binocular.js --no-open --no-server ./test
      shell: bash

    - name: Build
      run: npm run build
      shell: bash

    - name: Copy build artifacts
      run: cp -ar dist /home/runner/dist
      shell: bash

    - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: binocular_ui
          path: /home/runner/dist/

    - name: Checkout Repository
      uses: actions/checkout@v3
