# action.yml
name: 'Hubocular'
description: 'Mine your repo in you Actioins'
inputs:
  repo-name:  # id of input
    description: 'Repo name'
    required: true
  github-token:
    description: "Token to use for GitHub"
    required: true
runs:
  #using: 'docker'
  #image: 'Dockerfile'
  using: 'composite'
  steps:
    - run: echo "test" >> test.txt
      shell: bash
    - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: binocular_ui
          path: ./test.txt
  args:
    - ${{ inputs.repo-name }}
