on: [push]

env:
    REGISTRY: docker.io
    USER_NAME: schoeberlt
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test-action:
    runs-on: ubuntu-latest
    services:
      arangodb:
          image: arangodb:3.7
          ports:  
              - 8529:8529
          env: 
            ARANGO_ROOT_PASSWORD: openSesame
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
            registry: ${{ env.REGISTRY }}
            username: ${{ env.USER_NAME }}
            password: ${{ secrets.DOCKER_PAT }}
      - name: test  mining action
        uses: ./ # Uses an action in the root directory
        id: mine
        with:
          repo-name: 'https://github.com/INSO-TUWien/Binocular.git'

      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: binocular_ui
          path: ./
      # Use the output from the `hello` step
      #- name: Get the output time
        #run: echo "The time was ${{ steps.hello.outputs.time }}"
