on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: test  mining action
        uses: ./ # Uses an action in the root directory
        id: mine
        with:
          repo-name: 'https://github.com/schoeberlt/hubocular-test-action.git'
      # Use the output from the `hello` step
      #- name: Get the output time
        #run: echo "The time was ${{ steps.hello.outputs.time }}"
